import { z } from "zod";

export const CreateLeadSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email().optional().or(z.literal("")),
  phone: z.string().optional(),
  company: z.string().optional(),
  jobTitle: z.string().optional(),
  source: z.string().optional(),
  notes: z.string().optional(),
  assignedToId: z.string().optional(),
  disputeStatus: z.string().optional(),
  externalLeadId: z.string().optional(),
  orderId: z.string().optional(),
  received: z.string().optional(),
  fund: z.string().optional(),
  dateOfBirth: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zipCode: z.string().optional(),
  price: z.string().optional(),
  insuranceType: z.enum(["ACA", "MEDICARE_SUPPLEMENT", "MEDICARE_ADVANTAGE", "PART_D", "GROUP", "SHORT_TERM", "DENTAL_VISION", "LIFE", "OTHER"]).optional(),
  planType: z.string().optional(),
  policyStatus: z.enum(["ACTIVE", "GRACE_PERIOD", "LAPSED", "CANCELLED", "PENDING"]).optional(),
  policyRenewalDate: z.string().optional(),
  lastReviewDate: z.string().optional(),
  followUpDate: z.string().optional(),
  lifeEvent: z.string().optional(),
});

export const UpdateLeadSchema = z.object({
  firstName: z.string().min(1).optional(),
  lastName: z.string().min(1).optional(),
  email: z.string().email().optional().or(z.literal("")),
  phone: z.string().optional(),
  company: z.string().optional(),
  jobTitle: z.string().optional(),
  source: z.string().optional(),
  notes: z.string().optional(),
  status: z.enum(["NEW_LEAD", "CONTACTED", "QUOTED", "APPLICATION_SENT", "ENROLLED", "LOST"]).optional(),
  assignedToId: z.string().optional().nullable(),
  disputeStatus: z.string().optional(),
  externalLeadId: z.string().optional(),
  orderId: z.string().optional(),
  received: z.string().optional(),
  fund: z.string().optional(),
  dateOfBirth: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zipCode: z.string().optional(),
  price: z.string().optional(),
  insuranceType: z.enum(["ACA", "MEDICARE_SUPPLEMENT", "MEDICARE_ADVANTAGE", "PART_D", "GROUP", "SHORT_TERM", "DENTAL_VISION", "LIFE", "OTHER"]).optional().nullable(),
  planType: z.string().optional(),
  policyStatus: z.enum(["ACTIVE", "GRACE_PERIOD", "LAPSED", "CANCELLED", "PENDING"]).optional().nullable(),
  policyRenewalDate: z.string().optional(),
  lastReviewDate: z.string().optional(),
  followUpDate: z.string().optional(),
  lifeEvent: z.string().optional(),
});

export type CreateLeadInput = z.infer<typeof CreateLeadSchema>;
export type UpdateLeadInput = z.infer<typeof UpdateLeadSchema>;
